version: "3.7"
services:
  unicom24_db:
    container_name: unicom24_db
    image: postgres:latest
    environment:
      POSTGRES_DB: unicom24
      POSTGRES_USER: unicom24
      POSTGRES_PASSWORD: unicom24qwerty
    volumes:
      - pgdata:/var/lib/postgresql/data/

  unicom24_redis:
    container_name: unicom24_redis
    image: redis:latest
    ports:
      - "6376:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  unicom24_app:
    container_name: unicom24_app
    build: .
    command: bash -c "python manage.py migrate && uwsgi --ini uwsgi.ini"
    restart: always
    volumes:
      - api_data:/unicom24
    depends_on:
      - unicom24_db
      - unicom24_redis

  unicom24_celery:
    container_name: unicom24_celery
    build:
      context: .
      dockerfile: docker-celery
    command: celery -A unicom24 worker -l info
    restart: always
    volumes:
      - api_data:/unicom24
    depends_on:
      - unicom24_app
      - unicom24_db
      - unicom24_redis
  unicom24_nginx:
    container_name: unicom24_nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - api_data:/unicom24
      - ./log:/var/log/nginx
    depends_on:
      - unicom24_app
volumes:
  api_data:
  pgdata:

