version: '3'
services:
    unicom24_db:
      container_name: unicom24_db
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: password123
      # ports:
      #   - "5432:5432"
      #   (HOST:CONTAINER)
      volumes:
        - pgdata:/var/lib/postgresql/data/

    unicom24_nginx:
        container_name: unicom24_nginx
        build: ./nginx
        restart: always
        ports:
        - "80:80"
        volumes:
        - api_data:/unicom24
        - ./log:/var/log/nginx
        depends_on:
        - unicom24_app

    unicom24_app:
        container_name: unicom24_app
        build: .
        restart: always
        # command: uwsgi  --emperor uwsgi.ini
        command: uwsgi --ini uwsgi.ini
        # ports:
        # - "8002:8000"
        volumes:
        - api_data:/unicom24
        depends_on:
        - unicom24_db
volumes:
    api_data:
    pgdata:

