export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTRATION_BEGIN = 'REGISTRATION_BEGIN';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const GALLERY_OK = 'GALLERY_OK';
export const GALLERY_ERROR = 'GALLERY_ERROR';
export const GALLERYS_SET = 'GALLERYS_SET';
export const GALLERY_SET = 'GALLERY_SET';
export const GALLERY_ADD = 'GALLERY_ADD';
export const GALLERY_DEL = 'GALLERY_DEL';
export const GALLERY_CHOOSE = 'GALLERY_CHOOSE';

export const COMMENT_OK = 'COMMENT_OK';
export const COMMENT_ERROR = 'COMMENT_ERROR';
export const COMMENTS_SET = 'COMMENTS_SET';
export const COMMENT_SET = 'COMMENT_SET';
export const COMMENT_ADD = 'COMMENT_ADD';
export const COMMENT_DEL = 'COMMENT_DEL';
export const COMMENT_CHOOSE = 'COMMENT_CHOOSE';
